export interface EngineType {
  id: string;
  name: string;
  description: string;
  icon: string;
  details: string[];
  howItWorks: string;
  image: string;
}

export const ENGINES: EngineType[] = [
  {
    id: 'ice',
    name: 'Internal Combustion',
    description: 'The heart of most modern vehicles, converting fuel into motion through controlled explosions.',
    icon: 'Zap',
    details: ['Pistons', 'Crankshaft', 'Valves', 'Spark Plugs'],
    howItWorks: 'Fuel and air are compressed in a cylinder and ignited, pushing a piston down to create mechanical energy.',
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'electric',
    name: 'Electric Motor',
    description: 'Clean, efficient, and powerful. Converting electrical energy directly into rotational force.',
    icon: 'Battery',
    details: ['Stator', 'Rotor', 'Inverter', 'Battery Pack'],
    howItWorks: 'Magnetic fields generated by electricity pull and push a rotor, creating silent and instant torque.',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'jet',
    name: 'Jet Engine',
    description: 'Powering the skies by accelerating air to incredible speeds.',
    icon: 'Wind',
    details: ['Compressor', 'Combustor', 'Turbine', 'Nozzle'],
    howItWorks: 'Air is sucked in, compressed, mixed with fuel, ignited, and blasted out the back to create thrust.',
    image: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'steam',
    name: 'Steam Engine',
    description: 'The engine that started the Industrial Revolution.',
    icon: 'Cloud',
    details: ['Boiler', 'Cylinder', 'Piston', 'Flywheel'],
    howItWorks: 'Water is heated to create steam, which expands and pushes a piston to perform work.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800'
  }
];
